Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def read_data(ticker_list,
          start=dt.datetime(2019, 1, 2),
          end=dt.datetime(2019, 12, 31)):
    """
    This function reads in closing price data from Yahoo
    for each tick in the ticker_list.
    """
    ticker = pd.DataFrame()

    for tick in ticker_list:
        prices = data.DataReader(tick, 'yahoo', start, end)
        closing_prices = prices['Close']
        ticker[tick] = closing_prices

    return ticker

ticker = read_data(ticker_list)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/pandas_datareader/yahoo/daily.py[0m in [0;36m_read_one_data[0;34m(self, url, params)[0m
[1;32m    156[0m             [0mj[0m [0;34m=[0m [0mjson[0m[0;34m.[0m[0mloads[0m[0;34m([0m[0mre[0m[0;34m.[0m[0msearch[0m[0;34m([0m[0mptrn[0m[0;34m,[0m [0mresp[0m[0;34m.[0m[0mtext[0m[0;34m,[0m [0mre[0m[0;34m.[0m[0mDOTALL[0m[0;34m)[0m[0;34m.[0m[0mgroup[0m[0;34m([0m[0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 157[0;31m             [0mdata[0m [0;34m=[0m [0mj[0m[0;34m[[0m[0;34m"context"[0m[0;34m][0m[0;34m[[0m[0;34m"dispatcher"[0m[0;34m][0m[0;34m[[0m[0;34m"stores"[0m[0;34m][0m[0;34m[[0m[0;34m"HistoricalPriceStore"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    158[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'HistoricalPriceStore'

During handling of the above exception, another exception occurred:

[0;31mRemoteDataError[0m                           Traceback (most recent call last)
[0;32m<ipython-input-37-5b14cc9fd0c4>[0m in [0;36m<module>[0;34m[0m
[1;32m     15[0m     [0;32mreturn[0m [0mticker[0m[0;34m[0m[0;34m[0m[0m
[1;32m     16[0m [0;34m[0m[0m
[0;32m---> 17[0;31m [0mticker[0m [0;34m=[0m [0mread_data[0m[0;34m([0m[0mticker_list[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-37-5b14cc9fd0c4>[0m in [0;36mread_data[0;34m(ticker_list, start, end)[0m
[1;32m      9[0m [0;34m[0m[0m
[1;32m     10[0m     [0;32mfor[0m [0mtick[0m [0;32min[0m [0mticker_list[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 11[0;31m         [0mprices[0m [0;34m=[0m [0mdata[0m[0;34m.[0m[0mDataReader[0m[0;34m([0m[0mtick[0m[0;34m,[0m [0;34m'yahoo'[0m[0;34m,[0m [0mstart[0m[0;34m,[0m [0mend[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     12[0m         [0mclosing_prices[0m [0;34m=[0m [0mprices[0m[0;34m[[0m[0;34m'Close'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m         [0mticker[0m[0;34m[[0m[0mtick[0m[0;34m][0m [0;34m=[0m [0mclosing_prices[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/pandas/util/_decorators.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m    197[0m                 [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    198[0m                     [0mkwargs[0m[0;34m[[0m[0mnew_arg_name[0m[0;34m][0m [0;34m=[0m [0mnew_arg_value[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 199[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    200[0m [0;34m[0m[0m
[1;32m    201[0m         [0;32mreturn[0m [0mcast[0m[0;34m([0m[0mF[0m[0;34m,[0m [0mwrapper[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/pandas_datareader/data.py[0m in [0;36mDataReader[0;34m(name, data_source, start, end, retry_count, pause, session, api_key)[0m
[1;32m    374[0m [0;34m[0m[0m
[1;32m    375[0m     [0;32mif[0m [0mdata_source[0m [0;34m==[0m [0;34m"yahoo"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 376[0;31m         return YahooDailyReader(
[0m[1;32m    377[0m             [0msymbols[0m[0;34m=[0m[0mname[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    378[0m             [0mstart[0m[0;34m=[0m[0mstart[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/pandas_datareader/base.py[0m in [0;36mread[0;34m(self)[0m
[1;32m    251[0m         [0;31m# If a single symbol, (e.g., 'GOOG')[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    252[0m         [0;32mif[0m [0misinstance[0m[0;34m([0m[0mself[0m[0;34m.[0m[0msymbols[0m[0;34m,[0m [0;34m([0m[0mstring_types[0m[0;34m,[0m [0mint[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 253[0;31m             [0mdf[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_read_one_data[0m[0;34m([0m[0mself[0m[0;34m.[0m[0murl[0m[0;34m,[0m [0mparams[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0m_get_params[0m[0;34m([0m[0mself[0m[0;34m.[0m[0msymbols[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    254[0m         [0;31m# Or multiple symbols, (e.g., ['GOOG', 'AAPL', 'MSFT'])[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    255[0m         [0;32melif[0m [0misinstance[0m[0;34m([0m[0mself[0m[0;34m.[0m[0msymbols[0m[0;34m,[0m [0mDataFrame[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/quantecon/lib/python3.8/site-packages/pandas_datareader/yahoo/daily.py[0m in [0;36m_read_one_data[0;34m(self, url, params)[0m
[1;32m    158[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    159[0m             [0mmsg[0m [0;34m=[0m [0;34m"No data fetched for symbol {} using {}"[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 160[0;31m             [0;32mraise[0m [0mRemoteDataError[0m[0;34m([0m[0mmsg[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0msymbol[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0m__class__[0m[0;34m.[0m[0m__name__[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    161[0m [0;34m[0m[0m
[1;32m    162[0m         [0;31m# price data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mRemoteDataError[0m: No data fetched for symbol SNE using YahooDailyReader
RemoteDataError: No data fetched for symbol SNE using YahooDailyReader

